# Generated by Django 3.1.1 on 2020-11-20 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='logical_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventory'),
        ),
    ]
