# Generated by Django 3.1.1 on 2020-11-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201114_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
