# Generated by Django 3.1.1 on 2020-11-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201115_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
