# Generated by Django 3.1.1 on 2020-11-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.BooleanField(choices=[(None, 'Null'), (True, 'Listed'), (False, 'Unlisted')], null=True),
        ),
    ]
