# Generated by Django 3.1.1 on 2020-11-22 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201123_0554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inventory',
        ),
    ]
