# Generated by Django 3.1.1 on 2020-11-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201118_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='uid',
            new_name='logical_uid',
        ),
        migrations.RenameField(
            model_name='logging',
            old_name='uid',
            new_name='logical_uid',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.BooleanField(choices=[(True, 'Listed'), (False, 'Unlisted')], null=True),
        ),
        migrations.AlterField(
            model_name='logging',
            name='status',
            field=models.BooleanField(choices=[(True, 'Listed'), (False, 'Unlisted')]),
        ),
    ]
