# Generated by Django 3.1.1 on 2020-11-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('logical_uid', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
