# Generated by Django 3.1.1 on 2020-11-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='GN-001', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='qty',
            field=models.IntegerField(default='0'),
        ),
    ]
