# Generated by Django 3.1.1 on 2020-11-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201123_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
