# Generated by Django 3.1.1 on 2020-11-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201123_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='logging',
            name='warehouse',
            field=models.CharField(default='', max_length=144),
        ),
    ]
