# Generated by Django 3.1.1 on 2020-11-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201123_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='logical_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.inventory'),
        ),
    ]
