# Generated by Django 3.1.1 on 2020-11-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201123_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='logical_uid',
            field=models.CharField(default='', max_length=144),
        ),
    ]
