# Generated by Django 3.1.1 on 2020-11-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201123_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
