# Generated by Django 3.1.1 on 2020-11-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201125_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='logical_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inventory', to='api.inventory'),
        ),
    ]
