# Generated by Django 3.1.1 on 2020-11-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20201125_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logging',
            old_name='logical_uid',
            new_name='logical_uid_id',
        ),
    ]
