# Generated by Django 3.1.1 on 2020-11-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20201125_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logging',
            name='logical_uid_id',
        ),
        migrations.AddField(
            model_name='logging',
            name='logical_uid',
            field=models.CharField(default='', max_length=144),
        ),
    ]
