# Generated by Django 3.1.1 on 2020-11-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20201125_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.BooleanField(choices=[(True, 'Listed'), (False, 'Unlisted')], null=True),
        ),
    ]
