# Generated by Django 3.1.1 on 2020-12-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_inventory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='logging',
            name='status',
        ),
    ]
